#include <avr/io.h>

#include "PWM.h"

void pwm_init(void)
{
	PORTMUX.TCAROUTEA = PORTMUX_TCA0_PORTD_gc;
	TCA0.SINGLE.CTRLB = TCA_SINGLE_CMP0EN_bm | TCA_SINGLE_WGMODE_SINGLESLOPE_gc;
	TCA0.SINGLE.EVCTRL &= ~(TCA_SINGLE_CNTEI_bm);
	TCA0.SINGLE.PERBUF  = PWM_PERIOD;
	TCA0.SINGLE.CMP0BUF = DUTY_CYCLE_10;
	TCA0.SINGLE.CTRLA = TCA_SINGLE_CLKSEL_DIV64_gc | TCA_SINGLE_ENABLE_bm;
}